apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-bookstore-api
  labels:
    app: bookstore-api
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: bookstore-api
      release: {{ .Release.Name }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
