replicaCount: 1

image:
  repository: public.ecr.aws/xledbd/bookstore-api
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

awsSecretName: "aws-creds"
